// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsz0sCmw5VsstUBYvePkQDnF1I1p7k5tk',
    appId: '1:968112348329:web:39a157434bc8df375e9db8',
    messagingSenderId: '968112348329',
    projectId: 'ishop-spm',
    authDomain: 'ishop-spm.firebaseapp.com',
    storageBucket: 'ishop-spm.appspot.com',
    measurementId: 'G-H3Q8996885',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKMfQC451SgKCS2jk7wTkWbRKN4hdNdos',
    appId: '1:968112348329:android:d96c0d3623c816435e9db8',
    messagingSenderId: '968112348329',
    projectId: 'ishop-spm',
    storageBucket: 'ishop-spm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_hqZLAuuPge-ZMIMJ3adeDy6JPzHmCl4',
    appId: '1:968112348329:ios:06136bc95b9fa6cd5e9db8',
    messagingSenderId: '968112348329',
    projectId: 'ishop-spm',
    storageBucket: 'ishop-spm.appspot.com',
    iosBundleId: 'com.example.spmProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_hqZLAuuPge-ZMIMJ3adeDy6JPzHmCl4',
    appId: '1:968112348329:ios:06136bc95b9fa6cd5e9db8',
    messagingSenderId: '968112348329',
    projectId: 'ishop-spm',
    storageBucket: 'ishop-spm.appspot.com',
    iosBundleId: 'com.example.spmProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsz0sCmw5VsstUBYvePkQDnF1I1p7k5tk',
    appId: '1:968112348329:web:6ed1723ad7b9f2225e9db8',
    messagingSenderId: '968112348329',
    projectId: 'ishop-spm',
    authDomain: 'ishop-spm.firebaseapp.com',
    storageBucket: 'ishop-spm.appspot.com',
    measurementId: 'G-2TVNVY77HM',
  );

}